name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Vale
      uses: ./ # Uses an action in the root directory
      with:
        styles: |
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          https://github.com/errata-ai/Joblint/releases/latest/download/Joblint.zip
        config:
          https://gist.githubusercontent.com/jdkato/171186055d382c6065273fe5a7eeeb61/raw/4a795e30f9457337edec61387940b2ba76eb3dd6/.vale.ini
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
